//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShellBag.GUI.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShellBag.GUI.Localization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzername konnte nicht ermittelt werden! ähnelt.
        /// </summary>
        internal static string ShellBagsHelper_LoadSidsParallel_NoUsername {
            get {
                return ResourceManager.GetString("ShellBagsHelper_LoadSidsParallel_NoUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pfad: ähnelt.
        /// </summary>
        internal static string StartForm_ChangeToolStripLabelPath_Text {
            get {
                return ResourceManager.GetString("StartForm_ChangeToolStripLabelPath_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programm beenden ähnelt.
        /// </summary>
        internal static string StartForm_Close_Caption {
            get {
                return ResourceManager.GetString("StartForm_Close_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie das Programm wirklich beenden? ähnelt.
        /// </summary>
        internal static string StartForm_Close_Message {
            get {
                return ResourceManager.GetString("StartForm_Close_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzername: ähnelt.
        /// </summary>
        internal static string StartForm_ComboBoxChanged_Name {
            get {
                return ResourceManager.GetString("StartForm_ComboBoxChanged_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle eine verfügbare User-SID aus der Live-Registry: ähnelt.
        /// </summary>
        internal static string StartForm_ctr_combotxtDefault {
            get {
                return ResourceManager.GetString("StartForm_ctr_combotxtDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler: Konnte keine SIDs (User) ermitteln! ähnelt.
        /// </summary>
        internal static string StartForm_InitComboBox_Zero {
            get {
                return ResourceManager.GetString("StartForm_InitComboBox_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wählen Sie ein Kindelement aus der linken Seite. ähnelt.
        /// </summary>
        internal static string StartForm_LoadShellBags_datagridViewHintLabel {
            get {
                return ResourceManager.GetString("StartForm_LoadShellBags_datagridViewHintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade ShellBags... ähnelt.
        /// </summary>
        internal static string StartForm_LoadShellBags_Status {
            get {
                return ResourceManager.GetString("StartForm_LoadShellBags_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bereit! ähnelt.
        /// </summary>
        internal static string StartForm_Ready {
            get {
                return ResourceManager.GetString("StartForm_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (mit Administratorrechten) ähnelt.
        /// </summary>
        internal static string StartForm_Shown_AdminRights {
            get {
                return ResourceManager.GetString("StartForm_Shown_AdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (keine Administratorrechte!) ähnelt.
        /// </summary>
        internal static string StartForm_Shown_NoAdminRights {
            get {
                return ResourceManager.GetString("StartForm_Shown_NoAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte vorher nach ShellBag-Einträgen suchen! ähnelt.
        /// </summary>
        internal static string StartForm_TextDateitxtToolStripMenuItem_SearchPlease {
            get {
                return ResourceManager.GetString("StartForm_TextDateitxtToolStripMenuItem_SearchPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportieren fertig! ähnelt.
        /// </summary>
        internal static string StartForm_TextDateitxtToolStripMenuItem_Success {
            get {
                return ResourceManager.GetString("StartForm_TextDateitxtToolStripMenuItem_Success", resourceCulture);
            }
        }
    }
}
